name: CI Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual dispatch from the GitHub UI
  workflow_dispatch: {}

jobs:
  smoke:
    name: smoke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Set up JDK 17
        if: env.SKIP_SETUP_JAVA != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure adb and platform-tools available (for act/local)
        if: runner.os == 'Linux' && env.SKIP_ADB_INSTALL != 'true'
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y android-sdk-platform-tools android-tools-adb || true

      - name: Dump Android SDK and environment (debug)
        run: |
          chmod +x testing-tools/ci-debug-env.sh || true
          ./testing-tools/ci-debug-env.sh

      - name: Start Android emulator (ARM64 image) and run CI smoke script
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: arm64-v8a
          # run a debug dump first to inspect environment
          pre-emulator-launch-script: ./testing-tools/ci-debug-env.sh
          script: ./testing-tools/ci-smoke.sh emulator-5554
          # request explicit arm64 system image where supported
          system-image: 'system-images;android-31;google_apis;arm64-v8a'
          force-avd-creation: true
          emulator-options: -no-window -no-audio -verbose

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            app/build/reports/androidTests/connected/**
            /tmp/ci-*.log
            /tmp/ci-*.zip
