name: CI Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual dispatch from the GitHub UI
  workflow_dispatch: {}

jobs:
  smoke:
    name: smoke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure adb and platform-tools available (for act/local)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y android-sdk-platform-tools android-tools-adb || true

      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window -no-audio

      - name: Build APKs (release aab not needed here)
        run: |
          # Build after the emulator/SDK is available in the runner
          ./gradlew :Signal-Android:assembleDebug :Signal-Android:assembleAndroidTest --stacktrace --no-daemon

      - name: Run CI smoke script
        run: |
          chmod +x testing-tools/ci-smoke.sh || true
          ./testing-tools/ci-smoke.sh emulator-5554

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            app/build/reports/androidTests/connected/**
            /tmp/ci-*.log
            /tmp/ci-*.zip
